variables:
  DOTNET_SDK_VERSION: '2.2.105'
  DOTNET_PACKAGE_TYPE: 'sdk'
  RUBY_VERSION: '2.5'

jobs:
- template: build/tmpl/jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS 10.13'
    installRuby: 'false'

- template: build/tmpl/jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 16.04'

- template: build/tmpl/jobs.yml
  parameters:
    name: Windows
    vmImage: 'VS2017-Win2016'

 env: # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      NUGET_API_KEY: $(NUGET_API_KEY)
      NUGET_API_URL: $env:NUGET_API_URL
      CHOCOLATEY_API_KEY: $(CHOCOLATEY_API_KEY)
      CHOCOLATEY_API_URL: $(CHOCOLATEY_API_URL)
      RUBY_GEM_API_KEY: $(RUBY_GEM_API_KEY)
      TFX_TOKEN: $(TFX_TOKEN)
      CODECOV_TOKEN: $(CODECOV_TOKEN)
      ENABLED_UNIT_TESTS: $(ENABLED_UNIT_TESTS)
      ENABLED_PUBLISH_GEM: $(ENABLED_PUBLISH_GEM)
      ENABLED_PUBLISH_TFS: $(ENABLED_PUBLISH_TFS)
      ENABLED_PUBLISH_NUGET: $(ENABLED_PUBLISH_NUGET)
      ENABLED_PUBLISH_CHOCOLATEY: $(ENABLED_PUBLISH_CHOCOLATEY)
      ENABLED_PUBLISH_DOCKER: $(ENABLED_PUBLISH_DOCKER)